name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
         toolchain: ${{ matrix.rust-toolchain }}
         components: rustfmt
         override: true
    - name: Verify versions
      run: rustc --version && rustup --version && cargo --version
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Check code style
    run: cargo fmt -- --check
